import { AssessmentReport } from '@/types/skill-assessment';

export const generateSkillReport = (report: AssessmentReport): void => {
  // Create a simple HTML structure for the PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Skill Assessment Report</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #2563eb; padding-bottom: 20px; }
        .score-circle { width: 80px; height: 80px; border-radius: 50%; background: #2563eb; color: white; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px; font-size: 24px; font-weight: bold; }
        .section { margin-bottom: 30px; }
        .section h2 { color: #2563eb; border-bottom: 1px solid #e5e7eb; padding-bottom: 10px; }
        .results-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; }
        .result-item { border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; }
        .score-bar { height: 20px; background: #f3f4f6; border-radius: 10px; overflow: hidden; margin: 10px 0; }
        .score-fill { height: 100%; background: #2563eb; }
        .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
        .badge-beginner { background: #fef2f2; color: #991b1b; }
        .badge-intermediate { background: #fffbeb; color: #92400e; }
        .badge-advanced { background: #f0f9ff; color: #1e40af; }
        .recommendations { background: #f8fafc; padding: 20px; border-radius: 8px; }
        .course-item { margin: 10px 0; padding: 10px; border-left: 3px solid #2563eb; background: white; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Geospatial Skill Assessment Report</h1>
        <div class="score-circle">${report.overallScore}%</div>
        <p>Generated on ${new Date(report.generatedAt).toLocaleDateString()}</p>
      </div>

      <div class="section">
        <h2>Assessment Summary</h2>
        <div class="results-grid">
          ${report.results.map(result => `
            <div class="result-item">
              <h3>${result.category}</h3>
              <div class="badge badge-${result.level.toLowerCase()}">${result.level}</div>
              <div class="score-bar">
                <div class="score-fill" style="width: ${result.score}%"></div>
              </div>
              <p>Score: ${result.score}% (${result.correctAnswers}/${result.totalQuestions} correct)</p>
            </div>
          `).join('')}
        </div>
      </div>

      <div class="section">
        <h2>Strengths</h2>
        <ul>
          ${report.strengths.map(strength => `<li>${strength}</li>`).join('')}
        </ul>
      </div>

      <div class="section">
        <h2>Areas for Improvement</h2>
        <ul>
          ${report.weaknesses.map(weakness => `<li>${weakness}</li>`).join('')}
        </ul>
      </div>

      <div class="section">
        <h2>Learning Recommendations</h2>
        <div class="recommendations">
          ${report.recommendations.map(rec => `
            <div>
              <h3>${rec.skill} (${rec.priority} Priority)</h3>
              <p>Progress from ${rec.currentLevel} to ${rec.targetLevel}</p>
              ${rec.courses.map(course => `
                <div class="course-item">
                  <strong>${course.title}</strong> - ${course.duration}<br>
                  <small>${course.description}</small>
                </div>
              `).join('')}
            </div>
          `).join('')}
        </div>
      </div>

      <div class="footer">
        <p>This report was generated by Harita Hive Skill Assessment Tool</p>
        <p>Continue your learning journey at haritahive.com</p>
      </div>
    </body>
    </html>
  `;

  // Create a new window with the content
  const newWindow = window.open('', '_blank');
  if (newWindow) {
    newWindow.document.write(htmlContent);
    newWindow.document.close();
    
    // Trigger print dialog after a short delay to ensure content is loaded
    setTimeout(() => {
      newWindow.print();
    }, 1000);
  }
};