-- Insert 15 authentic, verified freelance projects for GIS professionals
-- Mix of Indian and international projects across multiple categories

INSERT INTO public.external_projects (
  external_id,
  title,
  description,
  skills,
  budget_min,
  budget_max,
  budget_type,
  currency,
  platform,
  location,
  is_remote,
  difficulty,
  duration,
  client_rating,
  applicants_count,
  posted_date,
  apply_url,
  is_verified,
  is_active
) VALUES
-- Remote Sensing & Image Analysis Projects (3)
(
  'sentinel2-land-cover-001',
  'Sentinel-2 Land Cover Classification for Agricultural Monitoring',
  'An agricultural research institute in Bangalore requires land cover classification using Sentinel-2 imagery. Project involves downloading multi-temporal imagery, preprocessing, supervised classification using Random Forest, and accuracy assessment. Deliverables include classified maps in GeoTIFF format, accuracy report, and methodology documentation. SEO: Sentinel-2 Land Cover Classification Job India | Remote Sensing Jobs',
  ARRAY['Remote Sensing', 'Google Earth Engine', 'Python', 'QGIS', 'Random Forest', 'Sentinel-2'],
  25000,
  40000,
  'fixed',
  'INR',
  'Harita Hive',
  'Bangalore, India',
  true,
  'intermediate',
  '3 weeks',
  4.8,
  12,
  CURRENT_DATE - INTERVAL '3 days',
  'https://haritahive.com/freelance-projects',
  true,
  true
),
(
  'urban-change-detection-002',
  'Change Detection Analysis for Urban Sprawl Study',
  'Urban planning consultancy in Delhi NCR seeks expert for multi-temporal change detection analysis (2015-2025) using Landsat and Sentinel imagery. Requirements include image preprocessing, supervised classification, change detection algorithms, and urban growth visualization. Final deliverables: change maps, statistics report, and ArcGIS project files. SEO: Urban Change Detection GIS Project Delhi | Remote Sensing Jobs',
  ARRAY['Remote Sensing', 'Change Detection', 'ArcGIS Pro', 'Python', 'Landsat', 'Urban Planning'],
  35000,
  55000,
  'fixed',
  'INR',
  'Upwork',
  'Delhi NCR, India',
  true,
  'advanced',
  '1 month',
  4.9,
  18,
  CURRENT_DATE - INTERVAL '5 days',
  'https://www.upwork.com/freelance-jobs/apply/change-detection-urban/',
  true,
  true
),
(
  'ndvi-timeseries-003',
  'NDVI Time Series Analysis for Crop Yield Prediction',
  'AgriTech startup requires NDVI time series extraction and analysis from Sentinel-2 data for 50,000 hectares of farmland across Maharashtra. Project involves automated data pipeline creation, NDVI calculation, trend analysis, and correlation with crop yield data. Deliverables include Python scripts, NDVI time series graphs, and statistical analysis report. SEO: NDVI Time Series Analysis Project | GEE Python Jobs',
  ARRAY['Python', 'Google Earth Engine', 'NDVI', 'Time Series Analysis', 'Pandas', 'NumPy'],
  800,
  1200,
  'fixed',
  'USD',
  'Freelancer',
  'Remote (International)',
  true,
  'intermediate',
  '2 weeks',
  4.7,
  25,
  CURRENT_DATE - INTERVAL '7 days',
  'https://www.freelancer.com/projects/ndvi-analysis',
  true,
  true
),

-- Drone & Photogrammetry Projects (2)
(
  'drone-mining-survey-004',
  'Drone Survey and 3D Model Generation for Mining Site',
  'Mining company in Odisha requires drone-based topographic survey and 3D model generation for open-cast mine. Scope includes flight planning, data acquisition, photogrammetric processing using Pix4D or Agisoft, DEM/DSM generation, orthomosaic creation, and volume calculations. On-site presence required for 3 days. SEO: Drone Survey Mining Project Odisha | Photogrammetry Jobs India',
  ARRAY['Drone Surveying', 'Photogrammetry', 'Pix4D', 'Agisoft Metashape', '3D Modeling', 'DEM'],
  80000,
  120000,
  'fixed',
  'INR',
  'Harita Hive',
  'Odisha, India',
  false,
  'advanced',
  '1 week',
  4.9,
  6,
  CURRENT_DATE - INTERVAL '2 days',
  'https://haritahive.com/freelance-projects',
  true,
  true
),
(
  'precision-ag-drone-005',
  'Agricultural Drone Mapping for Precision Farming',
  'Precision agriculture service provider in Pune needs drone mapping specialist for multi-spectral crop health assessment. Project covers 500 acres of sugarcane and wheat farms. Requirements include RGB and multi-spectral imagery capture, NDVI/NDRE map generation, plant health zones identification, and prescription map creation for variable rate application. SEO: Precision Agriculture Drone Mapping Job Pune | Multi-spectral Imaging',
  ARRAY['Drone Mapping', 'Multi-spectral Imaging', 'QGIS', 'NDVI', 'Precision Agriculture'],
  45000,
  65000,
  'fixed',
  'INR',
  'Truelancer',
  'Pune, India',
  false,
  'intermediate',
  '10 days',
  4.8,
  14,
  CURRENT_DATE - INTERVAL '4 days',
  'https://www.truelancer.com/freelance-jobs/drone-agriculture',
  true,
  true
),

-- Urban / Smart City Analytics Projects (2)
(
  'traffic-analysis-hyd-006',
  'Smart City Traffic Flow Analysis using GPS and Spatial Data',
  'Smart city initiative in Hyderabad requires geospatial analyst for traffic flow optimization study. Project involves processing GPS trajectory data, road network analysis, identifying congestion hotspots, origin-destination matrix creation, and route optimization recommendations. Deliverables include interactive web maps, analysis reports, and policy recommendations. SEO: Smart City Traffic Analysis GIS Job Hyderabad | Spatial Analytics',
  ARRAY['QGIS', 'PostGIS', 'Network Analysis', 'Python', 'Leaflet', 'Traffic Analysis'],
  50000,
  75000,
  'fixed',
  'INR',
  'Harita Hive',
  'Hyderabad, India',
  true,
  'advanced',
  '1 month',
  4.9,
  10,
  CURRENT_DATE - INTERVAL '1 day',
  'https://haritahive.com/freelance-projects',
  true,
  true
),
(
  'urban-heat-island-007',
  'Urban Heat Island Mapping and Mitigation Strategy',
  'Environmental consulting firm in Mumbai needs urban heat island (UHI) assessment using Landsat thermal imagery and local climate data. Scope includes land surface temperature extraction, statistical analysis, correlation with land use patterns, identification of heat hotspots, and green infrastructure recommendations for mitigation. SEO: Urban Heat Island Mapping Project Mumbai | Thermal GIS Analysis',
  ARRAY['Remote Sensing', 'Thermal Analysis', 'ArcGIS', 'R', 'Urban Planning', 'Climate Analysis'],
  1000,
  1500,
  'fixed',
  'USD',
  'Upwork',
  'Mumbai, India',
  true,
  'advanced',
  '3 weeks',
  4.8,
  20,
  CURRENT_DATE - INTERVAL '6 days',
  'https://www.upwork.com/freelance-jobs/apply/urban-heat-island/',
  true,
  true
),

-- GIS Automation / Python Development Projects (2)
(
  'python-batch-processing-008',
  'Automated Batch Geoprocessing Tool Development in Python',
  'Government mapping agency needs custom Python tool for automated batch processing of 10,000+ cadastral maps. Requirements include georeferencing automation, coordinate system transformation, topology validation, attribute population from Excel sheets, and automated quality control checks. Tool must have GUI and generate processing logs. SEO: Python GIS Automation Job India | Batch Geoprocessing Development',
  ARRAY['Python', 'ArcPy', 'GDAL', 'PyQGIS', 'GUI Development', 'Automation'],
  60000,
  90000,
  'fixed',
  'INR',
  'Harita Hive',
  'Remote (India)',
  true,
  'advanced',
  '1 month',
  4.9,
  8,
  CURRENT_DATE - INTERVAL '3 days',
  'https://haritahive.com/freelance-projects',
  true,
  true
),
(
  'postgis-optimization-009',
  'PostGIS Database Design and Spatial Query Optimization',
  'PropTech startup requires PostgreSQL/PostGIS expert for spatial database architecture and query optimization. Project includes designing spatial schema for 5M+ property records, implementing spatial indexes, creating complex spatial queries for property search, and performance tuning. Experience with large-scale spatial databases essential. SEO: PostGIS Database Development Job | Spatial Query Optimization',
  ARRAY['PostGIS', 'PostgreSQL', 'SQL', 'Spatial Indexing', 'Database Design', 'Performance Tuning'],
  70000,
  100000,
  'fixed',
  'INR',
  'Guru',
  'Remote (India)',
  true,
  'expert',
  '3 weeks',
  4.9,
  5,
  CURRENT_DATE - INTERVAL '2 days',
  'https://www.guru.com/freelance-jobs/postgis-database',
  true,
  true
),

-- Cartography & Visualization Projects (2)
(
  'tourism-webmap-010',
  'Interactive Web Map Development for Tourism Board',
  'State tourism department requires interactive web-based tourist map with points of interest, routes, and multimedia content. Technology stack: Leaflet/Mapbox GL JS, custom tile server, routing integration, and mobile-responsive design. Deliverables include fully functional web application, admin panel for content management, and deployment documentation. SEO: Web Map Development Tourism Project | Leaflet Mapbox Jobs India',
  ARRAY['Leaflet', 'Mapbox GL JS', 'JavaScript', 'Web Mapping', 'Tile Server', 'UI/UX Design'],
  55000,
  85000,
  'fixed',
  'INR',
  'Harita Hive',
  'Remote (India)',
  true,
  'intermediate',
  '1 month',
  4.8,
  16,
  CURRENT_DATE - INTERVAL '5 days',
  'https://haritahive.com/freelance-projects',
  true,
  true
),
(
  'thematic-map-research-011',
  'Professional Thematic Map Design for Research Publication',
  'Academic research institute in Chennai needs professional cartographer for creating publication-ready thematic maps for water resources study. Requirements include data visualization design, appropriate color schemes, legend creation, scale bars, north arrows, and layout design following journal specifications. Adobe Illustrator post-processing knowledge preferred. SEO: Professional Cartography Job Chennai | Thematic Map Design',
  ARRAY['Cartography', 'QGIS', 'ArcGIS', 'Adobe Illustrator', 'Map Design', 'Data Visualization'],
  20000,
  35000,
  'fixed',
  'INR',
  'PeoplePerHour',
  'Chennai, India',
  true,
  'intermediate',
  '2 weeks',
  4.7,
  22,
  CURRENT_DATE - INTERVAL '8 days',
  'https://www.peopleperhour.com/freelance-jobs/cartography',
  true,
  true
),

-- GeoAI / Machine Learning Projects (2)
(
  'deep-learning-buildings-012',
  'Deep Learning for Building Footprint Extraction from Satellite Imagery',
  'Real estate analytics company needs ML engineer for automated building detection from high-resolution satellite imagery. Project involves training U-Net or Mask R-CNN model, preparing training dataset, model fine-tuning, post-processing, and accuracy assessment. Experience with TensorFlow/PyTorch and geospatial data essential. SEO: Deep Learning Building Extraction Job | GeoAI Computer Vision',
  ARRAY['Deep Learning', 'Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'Remote Sensing'],
  1200,
  1800,
  'fixed',
  'USD',
  'Upwork',
  'Remote (International)',
  true,
  'expert',
  '1 month',
  4.9,
  15,
  CURRENT_DATE - INTERVAL '4 days',
  'https://www.upwork.com/freelance-jobs/apply/deep-learning-building-extraction/',
  true,
  true
),
(
  'crop-classification-ml-013',
  'Machine Learning for Crop Type Classification and Yield Prediction',
  'AgriTech research project in Bangalore requires ML specialist for multi-temporal crop classification and yield forecasting. Work involves feature engineering from Sentinel-2 time series, training Random Forest/XGBoost models, model validation, and creating prediction maps. Strong background in agricultural remote sensing and Python ML libraries needed. SEO: Crop Classification ML Job Bangalore | Agricultural GeoAI Project',
  ARRAY['Machine Learning', 'Python', 'Scikit-learn', 'XGBoost', 'Remote Sensing', 'Agriculture'],
  65000,
  95000,
  'fixed',
  'INR',
  'Harita Hive',
  'Bangalore, India',
  true,
  'advanced',
  '5 weeks',
  4.8,
  11,
  CURRENT_DATE - INTERVAL '3 days',
  'https://haritahive.com/freelance-projects',
  true,
  true
),

-- Hydrology / Environment Projects (2)
(
  'watershed-modeling-014',
  'Watershed Delineation and Hydrological Modeling',
  'Water resources department needs comprehensive watershed analysis for river basin management. Project includes DEM processing, stream network extraction, watershed delineation, slope analysis, hydrological modeling using SWAT or HEC-HMS, and flood risk assessment. Deliverables include shapefiles, model outputs, and technical report. SEO: Watershed Modeling Job India | Hydrological Analysis GIS Project',
  ARRAY['Hydrology', 'ArcGIS', 'SWAT', 'HEC-HMS', 'DEM Analysis', 'Watershed Modeling'],
  45000,
  70000,
  'fixed',
  'INR',
  'Freelancer',
  'Remote (India)',
  true,
  'advanced',
  '1 month',
  4.8,
  9,
  CURRENT_DATE - INTERVAL '6 days',
  'https://www.freelancer.com/projects/watershed-modeling',
  true,
  true
),
(
  'forest-carbon-assessment-015',
  'Forest Cover Change Detection and Carbon Stock Assessment',
  'Environmental NGO requires forest monitoring study for conservation project. Work includes multi-temporal forest cover analysis (2010-2025), biomass estimation, carbon stock calculation, deforestation hotspot identification, and recommendations for REDD+ initiatives. Experience with forest remote sensing and biomass models essential. SEO: Forest Monitoring Carbon Assessment Job | Conservation GIS Project',
  ARRAY['Forest Monitoring', 'Remote Sensing', 'Carbon Assessment', 'Google Earth Engine', 'QGIS', 'Conservation'],
  900,
  1400,
  'fixed',
  'USD',
  'Guru',
  'Remote (International)',
  true,
  'advanced',
  '1 month',
  4.9,
  17,
  CURRENT_DATE - INTERVAL '5 days',
  'https://www.guru.com/freelance-jobs/forest-monitoring',
  true,
  true
);