-- Insert 10 professional GIS tools for marketplace
DO $$
DECLARE
  admin_user_id UUID;
BEGIN
  SELECT id INTO admin_user_id FROM auth.users WHERE email = 'contact@haritahive.com' LIMIT 1;
  IF admin_user_id IS NULL THEN
    SELECT id INTO admin_user_id FROM auth.users LIMIT 1;
  END IF;

  INSERT INTO public.marketplace_tools (
    title, description, category, subcategory, tool_type, tech_stack, tags,
    download_url, github_url, demo_url, documentation_url, license_type, version,
    qgis_min_version, python_version, file_size_mb, is_free, base_price_usd, base_price_inr,
    is_featured, is_verified, download_count, rating, rating_count, author_id, created_by,
    status, metadata
  ) VALUES
  ('NDVI & Vegetation Health Analysis Toolkit',
   'Complete Python toolkit for calculating vegetation indices (NDVI, NDWI, EVI, SAVI) from Sentinel-2 and Landsat imagery. Includes automated cloud masking, temporal analysis, and change detection scripts optimized for agricultural monitoring.',
   'Remote Sensing', 'Vegetation Analysis', 'Script Package', 
   ARRAY['Python', 'QGIS', 'GDAL', 'rasterio'], 
   ARRAY['NDVI', 'RemoteSensing', 'Sentinel2', 'Agriculture'],
   'https://haritahive.com/downloads/ndvi-toolkit.zip', 
   'https://github.com/agrospatial/ndvi-toolkit',
   'https://demo.haritahive.com/ndvi-toolkit', 
   'https://docs.haritahive.com/ndvi-toolkit',
   'MIT License', '2.1.0', '3.0', '3.8+', 24, true, 0, 0,
   true, true, 2847, 4.8, 156, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'AgroSpatial Labs', 'offline_capable', true, 'includes_docs', true, 'includes_sample_data', true)),

  ('Sentinel-2 Atmospheric Correction Suite',
   'Professional-grade atmospheric correction implementing Sen2Cor algorithm for Level-1C to Level-2A processing. Removes atmospheric effects and generates analysis-ready surface reflectance products.',
   'Remote Sensing', 'Preprocessing', 'Plugin', 
   ARRAY['Python', 'QGIS', 'SNAP'], 
   ARRAY['AtmosphericCorrection', 'Sen2Cor', 'Preprocessing'],
   'https://haritahive.com/downloads/sen2cor-suite.zip', null,
   null, 'https://docs.haritahive.com/atmospheric-correction',
   'GPLv3', '1.4.2', '3.0', '3.8+', 75, false, 14.99, 749,
   false, true, 1653, 4.7, 98, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'EarthInsight Team', 'processing_speed', '100km² in ~12min', 'offline_capable', true)),

  ('Geospatial Data Cleaner & Validator',
   'Automated QA tool for vector and raster datasets. Detects and fixes topology errors, validates schemas, removes duplicates, standardizes projections, and generates comprehensive QA reports.',
   'Data Processing', 'Quality Assurance', 'Script Package',
   ARRAY['Python', 'QGIS', 'PostGIS'], 
   ARRAY['DataCleaning', 'QualityAssurance', 'Validation'],
   'https://haritahive.com/downloads/data-cleaner.zip', 
   'https://github.com/geoprecision/data-cleaner',
   'https://demo.haritahive.com/data-cleaner', 
   'https://docs.haritahive.com/data-validation',
   'MIT License', '3.0.1', '3.0', '3.7+', 18, true, 0, 0,
   true, true, 3124, 4.9, 287, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'GeoPrecision Tools', 'formats', ARRAY['Shapefile', 'GeoJSON', 'GeoPackage'], 'offline_capable', true)),

  ('Batch Raster Reprojection Tool',
   'High-performance batch processing for coordinate transformations and raster resampling. Processes thousands of rasters using parallel computing with 50+ projection systems and multiple resampling methods.',
   'Data Processing', 'Batch Processing', 'Script Package',
   ARRAY['Python', 'GDAL', 'QGIS'], 
   ARRAY['Reprojection', 'BatchProcessing', 'GDAL'],
   'https://haritahive.com/downloads/batch-reprojection.zip', null,
   null, 'https://docs.haritahive.com/raster-processing',
   'Commercial', '2.3.0', '3.0', '3.8+', 33, false, 9.99, 499,
   false, true, 892, 4.6, 67, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'Spatial Workflows Inc', 'performance', '8x faster', 'offline_capable', true)),

  ('Land Cover Classification using Random Forest',
   'Production ML pipeline for automated land cover classification. Pre-trained on 50,000+ samples across 12 LULC classes. Achieves 91% overall accuracy with feature engineering and post-classification refinement.',
   'Machine Learning', 'Classification', 'ML Model',
   ARRAY['Python', 'scikit-learn', 'QGIS'], 
   ARRAY['MachineLearning', 'LandCover', 'RandomForest'],
   'https://haritahive.com/downloads/rf-landcover.zip', 
   'https://github.com/geoai/landcover-rf',
   'https://demo.haritahive.com/rf-landcover', 
   'https://docs.haritahive.com/ml-classification',
   'CC-BY-NC', '1.8.0', null, '3.8+', 139, false, 19.99, 999,
   true, true, 1567, 4.9, 234, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'GeoAI Collective', 'accuracy', '91%', 'classes', 12, 'offline_capable', true)),

  ('Building Footprint Detection with Deep Learning',
   'U-Net CNN model for automated building extraction from high-resolution imagery. Trained on 100+ cities with 94% precision. Generates polygon footprints ready for GIS analysis. GPU-accelerated.',
   'Machine Learning', 'Object Detection', 'Deep Learning Model',
   ARRAY['Python', 'TensorFlow', 'PyTorch'], 
   ARRAY['DeepLearning', 'BuildingExtraction', 'CNN'],
   'https://haritahive.com/downloads/building-detection.zip', 
   'https://github.com/urbanai/building-detection',
   null, 'https://docs.haritahive.com/building-extraction',
   'Commercial', '2.0.1', null, '3.8+', 224, false, 24.99, 1249,
   true, true, 743, 4.8, 145, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'UrbanAI Labs', 'precision', '94%', 'gpu_required', true, 'offline_capable', true)),

  ('Watershed Delineation & Flow Analysis Toolkit',
   'Comprehensive hydrological modeling tools for watershed extraction, flow direction, accumulation, and stream network generation. Implements D8, D-Infinity, and MFD algorithms. Validated against USGS boundaries.',
   'Hydrology', 'Watershed Analysis', 'Plugin',
   ARRAY['Python', 'QGIS', 'GRASS GIS'], 
   ARRAY['Hydrology', 'Watershed', 'FlowAnalysis'],
   'https://haritahive.com/downloads/watershed-toolkit.zip', 
   'https://github.com/hydrogis/watershed-tools',
   null, 'https://docs.haritahive.com/hydrology-analysis',
   'GPLv3', '1.6.2', '3.0', '3.7+', 54, true, 0, 0,
   false, true, 2156, 4.7, 178, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'HydroGIS Solutions', 'algorithms', ARRAY['D8', 'D-Infinity', 'MFD'], 'offline_capable', true)),

  ('Flood Risk Assessment Tool',
   'Advanced flood hazard modeling combining DEM, rainfall, land cover, and soil data. Generates risk maps for 10, 50, 100-year floods with depth grids, velocity maps, and vulnerability assessments.',
   'Hydrology', 'Flood Modeling', 'Script Package',
   ARRAY['Python', 'R', 'HEC-RAS'], 
   ARRAY['FloodModeling', 'RiskAssessment', 'DisasterManagement'],
   'https://haritahive.com/downloads/flood-assessment.zip', null,
   null, 'https://docs.haritahive.com/flood-modeling',
   'Commercial', '2.1.0', null, '3.8+', 94, false, 16.99, 849,
   false, true, 1089, 4.8, 92, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'FloodGuard Analytics', 'return_periods', ARRAY['10yr', '50yr', '100yr'], 'offline_capable', true)),

  ('Interactive 3D Web Map Builder',
   'Complete web mapping framework for immersive 3D visualizations. Built on Cesium.js with terrain rendering, 3D buildings, time-series animation, and fly-through tours. Deploy-ready with Docker.',
   'Visualization', 'Web Mapping', 'Framework',
   ARRAY['JavaScript', 'Cesium.js', 'React'], 
   ARRAY['WebMapping', '3DVisualization', 'Cesium'],
   'https://haritahive.com/downloads/3d-webmap.zip', 
   'https://github.com/webgis/3d-map-builder',
   'https://demo.haritahive.com/3d-map', 
   'https://docs.haritahive.com/web-mapping',
   'MIT License', '1.5.0', null, null, 43, false, 11.99, 599,
   false, true, 645, 4.6, 54, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'WebGIS Innovators', 'deployment', 'Docker', 'offline_capable', false)),

  ('Road Network Analysis & Accessibility Tool',
   'Graph-based network analysis for transportation planning. Calculates shortest paths, service areas, route optimization, and OD matrices. Includes walkability scores and 15-minute city analysis.',
   'Analysis', 'Transportation', 'Script Package',
   ARRAY['Python', 'PostGIS', 'pgRouting'], 
   ARRAY['NetworkAnalysis', 'Transportation', 'Accessibility'],
   'https://haritahive.com/downloads/network-analysis.zip', 
   'https://github.com/transportgis/network-tools',
   'https://demo.haritahive.com/network-analysis', 
   'https://docs.haritahive.com/transport-network',
   'MIT License', '2.2.0', '3.0', '3.7+', 28, true, 0, 0,
   true, true, 1893, 4.9, 201, admin_user_id, admin_user_id, 'active',
   jsonb_build_object('provider_name', 'TransportGIS Pro', 'algorithms', ARRAY['Dijkstra', 'A-Star'], 'osm_compatible', true));

END $$;